/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_robaho_jnatsd_util_ChannelIO */

#ifndef _Included_com_robaho_jnatsd_util_ChannelIO
#define _Included_com_robaho_jnatsd_util_ChannelIO
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_robaho_jnatsd_util_ChannelIO
 * Method:    write0
 * Signature: (IJI)I
 */
JNIEXPORT jint JNICALL Java_com_robaho_jnatsd_util_ChannelIO_write0
  (JNIEnv *, jclass, jint, jlong, jint);

/*
 * Class:     com_robaho_jnatsd_util_ChannelIO
 * Method:    read0
 * Signature: (IJI)I
 */
JNIEXPORT jint JNICALL Java_com_robaho_jnatsd_util_ChannelIO_read0
  (JNIEnv *, jclass, jint, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
